src/core/urls.py
from django.conf.urls import url
from core.views import DocsView, HomeView, HowItWorksView, LicenseView

urlpatterns = [

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^how-it-works$', HowItWorksView.as_view(), name='how_it_works'),
    url(r'^docs$', DocsView.as_view(), name='docs'),
    url(r'^license$', LicenseView.as_view(), name='license'),
]

src/dynamics/urls.py
from django.conf.urls import url
from dynamics.views import new_dynamic, attach_molecules, load_dynamics, include_molecules, run_alignment, run_lqtagrid, lqtagrid_box


urlpatterns = [


    url(r'^new/$', new_dynamic, name='new_dynamic'),
    #url(r'^(?P<dynamic_id>[0-9]+)/new/$', new_dynamic, name='new_dynamic'),
    url(r'^(?P<dynamic_id>[0-9]+)/include-molecules/$', include_molecules, name='include_molecules'),
    url(r'^load-dynamics/$', load_dynamics, name='load_dynamics'),
    url(r'^attach-molecules/$', attach_molecules,
        name='attach_molecules'),
    url(r'^(?P<dynamic_id>[0-9]+)/run-alignment/$', run_alignment,
        name='run_alignment'),
    url(r'^(?P<dynamic_id>[0-9]+)/run-lqtagrid/$', run_lqtagrid,
        name='run_lqtagrid'),
    url(r'^(?P<dynamic_id>[0-9]+)/(?P<run_alignment>\d+)/(?P<run_dynamics>\d+)/lqtagrid-box/$', lqtagrid_box,
        name='lqtagrid_box'),
]

src/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^register/$', views.RegistrationView.as_view(), name="register"),
]

src/web-4d-qsar/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()


urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^dynamics/', include('dynamics.urls', namespace='dynamics')),
    url(r'^matrix/', include('matrix_generate.urls',
                             namespace='matrix_generate')),
    url(r'', include('core.urls', namespace='core')),
    url(r'^users/', include('users.urls', namespace='users')),
]

src/web4dqsar/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'', include('core.urls', namespace='core')),
)

src/core/models.py
from django.db import models

# Create your models here.

src/core/views.py
from django.views.generic import RedirectView, TemplateView


class HomeView(TemplateView):
    template_name = 'core/home.html'


class HowItWorksView(TemplateView):
    template_name = 'core/how_it_works.html'


class DocsView(RedirectView):
    url = 'http://lqta.iqm.unicamp.br/portugues/siteLQTA/LQTAgrid.html'
    permanent = False


class LicenseView(TemplateView):
    template_name = 'core/license.html'

src/core/templates/core/docs.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header">
    <h1>{% trans 'Documentation' %}</h1>
    <p class="lead">Toda documentação do projeto foi criada em <a href="">Sphinx</a> e está hospedada no <a href="">Read the Docs</a>.</p>
</div>
{% endblock %}

src/core/templates/core/home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block head_js %}
<style>
</style>
{% endblock %}

{% block content %}
<nav class="navbar navbar-default w-navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Wiki</a></li>
        <li><a href="#">Documentation</a></li>
        <li><a href="#">License</a></li>
        <li><a href="#">Contact</a></li>
        <li><a href="#">Help</a></li>
        <li><a href="{% url 'users:register' %}">Register</a></li>
        {% if not user.is_authenticated %}
          <li><a href="{% url 'users:login' %}">Login</a></li>
        {% endif %}
        {% if user.is_authenticated %}
          <li><a href="{% url 'users:logout' %}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div class="jumbotron w-jumbotron">
    <div class="container w-jumbotron-container">
        <h1>Web 4D-QSAR</h1>
        <p>{% trans "An open source project that generates 4D QSAR descriptors" %}</p>
    </div>
</div>
<div class="container w-main-links">
    <a class="btn btn-success btn-lg" href="{% url 'dynamics:new_dynamic' %}" role="button">{% trans "New Dynamic" %}</a>
    <a class="btn btn-success btn-lg" href="{% url 'dynamics:load_dynamics' %}" role="button">{% trans "Load Dynamic" %}</a>
    <a class="btn btn-default btn-lg" href="https://github.com/rougeth/web-4d-qsar" role="button">{% trans "View on GitHub" %}</a>
</div>
<hr>
<div class="row">
    <div class="container">
        <div class="col-md-4">
            <h4>Open source</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam earum dolores repudiandae similique soluta vitae veritatis eos vel laudantium.</p>
        </div>
        <div class="col-md-4">
            <h4>Distributed</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam earum dolores repudiandae similique soluta vitae veritatis eos vel laudantium.</p>
        </div>
        <div class="col-md-4">
            <h4>Fast</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam earum dolores repudiandae similique soluta vitae veritatis eos vel laudantium.</p>
        </div>
    </div>
</div>



{% endblock %}

src/core/templates/core/how_it_works.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="page-header">
    <h1>{% trans "How Web-4D-QSAR works" %}</h1>
</div>
<p>
The creation of pharmacos with the aid of computing is a research area of great importance in chemistry and related fields.</p>
<p>
The toolkit is available for this purpose, among others, in programs for generating descriptors and construction and validation of mathematical models in QSAR (English, Quantitative Structure-Activity Relationship). Aiming to make this more accessible to the scientific community, new methodologies and programs were developed <a href="{% url 'core:docs' %}">(MARTINS, 2013)</a> study. Including a new 4D QSAR methodology, known as LQTA-QSAR, whose goal is to generate spatial descriptors taking into account the profiles of conformational sampling of molecules under study obtained from molecular dynamics simulations.
</p>
<img src="{% static 'imgs/LQTAGridPy.png' %}" alt="">
<p>Based on these methodologies developed, a Web platform was created to provide an integrated environment for performing molecular dynamics and generation of system descriptors.
</p>
{% endblock %}

src/core/templates/core/license.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="page-header">
    <h1>{% trans 'License' %}</h1>
    <p class="lead">License name</p>
</div>
<p>
    Copyright (C) 2014
</p>
<p>
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
</p>
<p>
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
</p>
<p>
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
</p>
{% endblock %}