src/core/urls.py
from django.conf.urls import url
from core.views import DocsView, HomeView, HowItWorksView, LicenseView

urlpatterns = [

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^how-it-works$', HowItWorksView.as_view(), name='how_it_works'),
    url(r'^docs$', DocsView.as_view(), name='docs'),
    url(r'^license$', LicenseView.as_view(), name='license'),
]

src/dynamics/urls.py
from django.conf.urls import url
from dynamics.views import new_dynamic, attach_molecules, load_dynamics, include_molecules, run_alignment, run_lqtagrid, lqtagrid_box


urlpatterns = [


    url(r'^new/$', new_dynamic, name='new_dynamic'),
    #url(r'^(?P<dynamic_id>[0-9]+)/new/$', new_dynamic, name='new_dynamic'),
    url(r'^(?P<dynamic_id>[0-9]+)/include-molecules/$', include_molecules, name='include_molecules'),
    url(r'^load-dynamics/$', load_dynamics, name='load_dynamics'),
    url(r'^attach-molecules/$', attach_molecules,
        name='attach_molecules'),
    url(r'^(?P<dynamic_id>[0-9]+)/run-alignment/$', run_alignment,
        name='run_alignment'),
    url(r'^(?P<dynamic_id>[0-9]+)/run-lqtagrid/$', run_lqtagrid,
        name='run_lqtagrid'),
    url(r'^(?P<dynamic_id>[0-9]+)/(?P<run_alignment>\d+)/(?P<run_dynamics>\d+)/lqtagrid-box/$', lqtagrid_box,
        name='lqtagrid_box'),
]

src/web-4d-qsar/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()


urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^dynamics/', include('dynamics.urls', namespace='dynamics')),
    url(r'^matrix/', include('matrix_generate.urls',
                             namespace='matrix_generate')),
    url(r'', include('core.urls', namespace='core')),
    url(r'^users/', include('users.urls', namespace='users')),
]

src/web4dqsar/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'', include('core.urls', namespace='core')),
)

src/dynamics/models.py
from django.db import models
from django import forms
from multiselectfield import MultiSelectField
from users.models import MyUser
import re


def path_builder(instance, filename):
    filename = re.sub('[^a-zA-Z0-9\-\.]', '_', filename)

    return 'files/dynamics/{}/{}/{}'.format(
        instance.dynamic.user.email,
        instance.dynamic.id,
        filename
    )


class Box(models.Model):

    # Box Information
    box_dimension_x = models.IntegerField(default=0)
    box_dimension_y = models.IntegerField(default=0)
    box_dimension_z = models.IntegerField(default=0)
    box_coordinate_x = models.IntegerField(default=0)
    box_coordinate_y = models.IntegerField(default=0)
    box_coordinate_z = models.IntegerField(default=0)
    step = models.FloatField(default=1.0)

    # Probe
    CHOICES = (('COO-', 'COO-'),
               ('NH3+', 'NH3+'),
               ('CH3-', 'CH3-'),
               ('Ar(C-H)', 'Ar(C-H)'),
               ('O-H', 'O-H'),
               ('NH2', 'NH2'),
               ('Ar(N-H)', 'Ar(N-H)'),
               ('C=O', 'C=O'),
               ('NH2(ARG)', 'NH2(ARG)'),
               ('(H2O)HO', '(H2O)HO'),
               ('Zn2+', 'Zn2+'),
               ('Cl-', 'Cl-'),
               ('Na+', 'Na+'),)
    #probe = MultiSelectField(choices=CHOICES, widget=forms.CheckboxSelectMultiple())
    probe = MultiSelectField(choices=CHOICES)


class Dynamic(models.Model):
    # name = models.CharField(max_length=50)
    # email = models.EmailField()
    user = models.ForeignKey(MyUser)
    lqtagrid_box = models.ForeignKey(Box, default=None, null=True, blank=True)

    # Dynamic params
    box_size = models.IntegerField(default=10)
    number_of_molecules = models.IntegerField()
    number_of_atoms_for_alignment = models.IntegerField()

    # Flags
    configured = models.BooleanField(default=False)
    process_finished = models.BooleanField(default=False)
    email_sent = models.BooleanField(default=False)
    run_dynamics = models.BooleanField(default=True)
    run_alignment = models.BooleanField(default=False)
    run_lqtagrid = models.BooleanField(default=False)

    started = models.DateField(auto_now_add=True)


class Molecule(models.Model):
    dynamic = models.ForeignKey(Dynamic)
    file = models.FileField(upload_to=path_builder)
    atoms = models.CharField(max_length=100)

    # Flag
    reference = models.BooleanField(default=False)
    # Flag
    dynamic_executed = models.BooleanField(default=False)
    alignment_executed = models.BooleanField(default=False)
    lqtagrid_executed = models.BooleanField(default=False)

src/dynamics/forms.py
from django import forms

from dynamics.models import Dynamic, Box


class DynamicForm(forms.ModelForm):
    class Meta:
        model = Dynamic
        fields = ['box_size', 'number_of_molecules',
                  'number_of_atoms_for_alignment', 'run_alignment', 'run_lqtagrid']

    # def clean(self):
    #     cleaned_data = super(DynamicForm, self).clean()
    #     cleaned_data['number_of_molecules'] = 0
    #     return cleaned_data


class MoleculeForm(forms.Form):
    file = forms.FileField(required=True)
    atoms = forms.CharField(max_length=40)


class IncludeMoreMoleculesForm(forms.Form):
    number_of_molecules = forms.IntegerField()


class RunAlignmentMoleculeForm(forms.Form):
    atoms = forms.CharField(max_length=40)


class BoxForm(forms.ModelForm):
    class Meta:
        model = Box
        fields = ['box_dimension_x', 'box_dimension_y', 'box_dimension_z',
                  'box_coordinate_x', 'box_coordinate_y', 'box_coordinate_z',
                  'step', 'probe']

src/dynamics/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect#, JsonResponse
from django.forms.formsets import formset_factory
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required

from dynamics.models import Dynamic, Molecule
from dynamics.forms import DynamicForm, MoleculeForm, IncludeMoreMoleculesForm, RunAlignmentMoleculeForm, BoxForm
from dynamics import tasks

#from django.forms.models import model_to_dict
from django.core import serializers

@login_required(login_url='/users/login/')
def new_dynamic(request):
    """ Step 1
        Set basic configurations.
    """

    if request.method == 'POST':
        dynamic_form = DynamicForm(request.POST)

        if dynamic_form.is_valid():
            new_dynamic = dynamic_form.save(commit=False)
            new_dynamic.user = request.user
            new_dynamic.save()
            request.session['dynamic_id'] = new_dynamic.id
            return HttpResponseRedirect('/dynamics/attach-molecules')
        else:
            context = {
                'dynamic_form': dynamic_form,
            }
            return render(request, 'dynamics/new_dynamic.html', context)
    # if dynamic_id is None:
    context = {
        'dynamic_form': DynamicForm(),
    }
    # else:
        # dynamic = Dynamic.objects.get(pk=dynamic_id)
        # dynamic_form = DynamicForm(instance=dynamic)
        # dynamic_form.fields['box_size'].disabled = True
        # dynamic_form.fields['number_of_molecules'].label = 'Number of molecules to be added'
        # dynamic_form.fields['number_of_atoms_for_alignment'].disabled = True
        # context = {
        #     'dynamic_form': dynamic_form,
        # }
    return render(request, 'dynamics/new_dynamic.html', context)

@login_required(login_url='/users/login/')
def load_dynamics(request):
    dynamics = Dynamic.objects.filter(user=request.user).order_by('id')
    return render(request, 'dynamics/list_dynamic.html', {'dynamics': dynamics})

@login_required(login_url='/users/login/')
def include_molecules(request,dynamic_id):
    """
        Include more molecules to an existing dynamic
    """
    dynamic = Dynamic.objects.get(pk=dynamic_id)

    if request.method == 'POST':
        include_molecules_form = IncludeMoreMoleculesForm(request.POST)

        if include_molecules_form.is_valid():
            number_of_molecules = include_molecules_form.cleaned_data['number_of_molecules']
            dynamic.number_of_molecules += number_of_molecules
            dynamic.run_dynamics = True
            dynamic.save()
            request.session['dynamic_id'] = dynamic_id
            return HttpResponseRedirect('/dynamics/attach-molecules')
        else:
            context = {
                'include_molecules_form': include_molecules_form,
                'dynamic_id': dynamic_id,
                'number_of_existing_molecules': dynamic.number_of_molecules,
            }
            return render(request, 'dynamics/include_molecules.html', context)
    context = {
        'include_molecules_form': IncludeMoreMoleculesForm(),
        'dynamic_id': dynamic_id,
        'number_of_molecules': dynamic.number_of_molecules,
    }
    return render(request, 'dynamics/include_molecules.html', context)

@login_required(login_url='/users/login/')
def attach_molecules(request):
    """ Step 2
        Send molecules files and configure the atoms that should be used to
        alignment.
    """

    dynamic_id = request.session.get('dynamic_id')
    dynamic_form = DynamicForm(request.POST)
    if not dynamic_id:
        request.session['dynamic_id'] = None
        return HttpResponseRedirect('/dynamics/new')

    dynamic = Dynamic.objects.filter(id=dynamic_id)[0]
    # if dynamic.configured:
    #     request.session['dynamic_id'] = None
    #     return HttpResponseRedirect('/dynamics/new')

    molecules_attached = Molecule.objects.filter(dynamic=dynamic)
    molecules_to_attach = dynamic.number_of_molecules-len(molecules_attached)

    # aqui começa minha tentativa de preencher formset
    # molecules = Molecule.objects.filter(dynamic=dynamic)
    #
    # m_formset_initial = []
    #
    # for m in molecules:
    #     m_formset_initial.append({'file': m.file, 'atoms': m.atoms})
    #
    # if flag:
    #     dynamic.run_alignment = True
    #     dynamic.run_dynamics = False
    #     MoleculeFormSet = formset_factory(MoleculeForm, extra=0)
    #     molecule_formset = MoleculeFormSet(initial=m_formset_initial)
    #     # for form in molecule_formset:
    #     #     form.fields['file'].disabled = True
    # else:
    #         molecule_formset = formset_factory(
    #             MoleculeForm,
    #             extra=molecules_to_attach
    #         )
    # aqui termina

    molecule_formset = formset_factory(
        MoleculeForm,
        extra=molecules_to_attach
    )

    if request.method == 'GET':
        context = {
            'molecule_formset': molecule_formset,
            'dynamic_form': dynamic_form,
            'max_atoms_selected': dynamic.number_of_atoms_for_alignment,
            'total_number_of_molecules': dynamic.number_of_molecules,
            'molecules_to_attach': molecules_to_attach,
            'molecules_attached': molecules_attached,
        }

        return render(request, 'dynamics/attach_dynamic_files.html', context)
    else:
        dynamic.run_alignment = request.POST.get('run_alignment', '') == 'on'
        dynamic.run_lqtagrid = request.POST.get('run_lqtagrid', '') == 'on'
        dynamic.run_dynamics = True
        print('(run_alignment, run_lqtagrid) : (%s,%s)' % (dynamic.run_alignment, dynamic.run_lqtagrid))
        return attach_molecules_post(request, dynamic)


def attach_molecules_post(request, dynamic):

    molecule_formset = formset_factory(
        MoleculeForm,
        extra=dynamic.number_of_molecules
    )
    molecule_formset = molecule_formset(request.POST, request.FILES)

    if not molecule_formset.is_valid():
        context = {
            'molecule_formset': molecule_formset,
            'max_atoms_selected': dynamic.number_of_atoms_for_alignment
        }
        return render(request, 'dynamics/attach_dynamic_files.html',
                      context)

    else:
        reference = int(request.POST.get('reference-molecule'))

        for i, f in enumerate(molecule_formset):
            if reference == i:
                ref = True
            else:
                ref = False

            new_molecule = Molecule(
                dynamic=dynamic,
                file=f.cleaned_data['file'],
                atoms=f.cleaned_data['atoms'],
                reference=ref,
            )
            new_molecule.save()

        molecules = Molecule.objects.filter(dynamic=dynamic)
        for i, m in enumerate(molecules):
            if reference == i:
                molecules[i].reference = True
            else:
                molecules[i].reference = False
            molecules[i].save()

        dynamic.configured = True
        dynamic.save()
        request.session['dynamic_id'] = None

        if dynamic.run_lqtagrid:
            run_lqtagrid = 1 if dynamic.run_lqtagrid else 0
            run_alignment = 1 if dynamic.run_alignment or dynamic.run_lqtagrid else 0
            return HttpResponseRedirect(reverse('dynamics:lqtagrid_box', args=[dynamic.id, run_alignment, run_lqtagrid]))

        # Starts the task to process the new dynamic
        #tasks.molecular_dynamics.delay(dynamic)
        #tasks.molecular_dynamics.delay(model_to_dict(dynamic) )
        #serializers.serialize("xml", SomeModel.objects.all())
        tasks.molecular_dynamics.delay(serializers.serialize("json", [dynamic]))

        context = {
            'name': dynamic.user.first_name,
            'email': dynamic.user.email,
        }
        return render(request, 'dynamics/dynamic_started.html', context)


@login_required(login_url='/users/login/')
def run_alignment(request, dynamic_id):
    """ Step 2
        Send molecules files and configure the atoms that should be used to
        alignment.
    """

    request.session['dynamic_id'] = dynamic_id
    #dynamic_form = DynamicForm(request.POST)

    dynamic = Dynamic.objects.filter(id=dynamic_id)[0]
    dynamic.run_lqtagrid = False
    dynamic_form = DynamicForm(instance=dynamic)

    # if dynamic.configured:
    #     request.session['dynamic_id'] = None
    #     return HttpResponseRedirect('/dynamics/new')

    molecules = Molecule.objects.filter(dynamic=dynamic)

    m_formset_initial = []

    for m in molecules:
        m_formset_initial.append({'atoms': m.atoms})

    dynamic.run_alignment = True
    dynamic.run_dynamics = False
    #print("Valido dynamic form "+str(dynamic_form.is_valid()))
    # if dynamic_form.is_valid():
    #     print(dynamic_form.cleaned_data['run_lqtagrid'])
    #     # dynamic.run_lqtagrid = dynamic_form.cleaned_data['run_lqtagrid']
    # else:
    #     print(dynamic_form.errors)
    RunAlignmentMoleculeFormSet = formset_factory(RunAlignmentMoleculeForm, extra=0)
    molecule_formset = RunAlignmentMoleculeFormSet(initial=m_formset_initial)

    if request.method == 'GET':
        context = {
            'molecule_formset': molecule_formset,
            'dynamic_form': dynamic_form,
            'max_atoms_selected': dynamic.number_of_atoms_for_alignment,
            'total_number_of_molecules': dynamic.number_of_molecules,
            'molecules_attached': zip(molecules, molecule_formset)
        }

        return render(request, 'dynamics/run_alignment.html', context)
    else:
        dynamic.run_lqtagrid = request.POST.get('run_lqtagrid', '') == 'on'
        return run_alignment_post(request, dynamic)


def run_alignment_post(request, dynamic):

    molecule_formset = formset_factory(
        RunAlignmentMoleculeForm,
        extra=dynamic.number_of_molecules
    )
    molecule_formset = molecule_formset(request.POST)

src/dynamics/templates/dynamics/attach_dynamic_files.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load widget_tweaks %}

{% block head_js %}
<link rel="stylesheet" href="{% static "third-party/magicsuggest/magicsuggest-min.css" %}">
{% endblock %}

{% block footer_js %}
<script src="{% static "third-party/magicsuggest/magicsuggest-min.js" %}"></script>
<script>
    $('#molecules-form').submit(function(event) {

        var numeric_atoms_input_re = /^(\d+)(,\d+)*$/;
        var number_of_inputs = $('#id_form-TOTAL_FORMS').val();
        var i;

        for(i=0; i<number_of_inputs; i++) {
            var input = $('#id_form-' + i + '-atoms').val();
            input = input.replace(/ /g,'');

            if(!numeric_atoms_input_re.test(input) ||
                input.split(',').length != {{ max_atoms_selected }}) {

                $('#id_form-' + i + '-atoms').parent().parent().addClass('has-error');
                $('#id_form-' + i + '-atoms').focus();
                event.preventDefault();
                return false;
            }
        }
        this.submit();
    });
</script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h1>{% trans "Attach Molecules" %}</h1>
        <p class="lead">{% trans 'On this page you must insert the reference molecules to the dynamics and alignments.' %}</p>
        <form id="molecules-form" class="form-horizontal" role="form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="reference-molecule" class="col-sm-3 control-label">{% trans 'Reference' %}</label>
                <div class="col-sm-9">
                    <select id="" name="reference-molecule" class="form-control">
                    {% for f in molecule_formset %}
                    <option value="{{ forloop.counter0 }}">{% trans 'Molecule' %} #{{ forloop.counter }}</option>
                    {% endfor %}
                    </select>
                </div>
            </div>
            {{ molecule_formset.management_form }}
            {% for f in molecule_formset %}
            <hr>

            {% if f.file.errors %}
            <div class="form-group file-input has-error">
            {% else %}
            <div class="form-group file-input">
            {% endif %}
                <label for="{{ f.file.id_for_label }}" class="col-sm-3 control-label">Molecule #{{ forloop.counter}}</label>
                <div class="col-sm-9">
                    {{ f.file.errors }}
                    {{ f.file }}
                    <p class="help-block">{% trans 'The format of the file must be \'.mol2\'.' %}</p>
                </div>
            </div>
            <div class="form-group atoms-input">
                <label for="{{ f.atoms.id_for_label }}" class="col-sm-3 control-label">Atoms</label>
                <div class="col-sm-9">
                    {{ f.atoms.errors }}
                    {{ f.atoms|add_class:'numeric-atom' }}
                </div>
            </div>
            {% endfor %}
            <div class="form-group">
                <label for="" class="col-sm-3 control-label"></label>
                <div class="col-sm-offset-3 col-sm-9">
                    <button type="submit" class="btn btn-default">{% trans 'Start Dynamic' %}</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-3"></div>
</div>
{% endblock %}

src/dynamics/templates/dynamics/dynamic_started.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="page-header">
    <h1>{% trans "Dynamic request sent" %}</h1>
    <p class="lead">Hi {{ name }}! We received your dynamic request and it is already in the queue for execution. Once it get finished we will send an email with the results to this address: <i>{{ email }}</i>.</p>
</div>
{% endblock %}

src/dynamics/templates/dynamics/include_molecules.html
{% extends 'base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h1>{% trans 'Include more molecules to your dynamic' %}</h1>
        <form class="form" role="form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ include_molecules_form.non_field_errors }}
            <h2>Contact</h2>
              {% if user.is_authenticated %}
                <p class="lead"> {{ user.first_name }} </p>
                <p class="lead"> {{ user.email }} </p>
              {% else %}
                <p class="lead"> Usuário anônimo </p>
              {% endif %}
            <span class="help-block">{% trans 'We will use this email address to contact you when the dynamic is ready.' %}</span>
            <h2>Dynamic Data</h2>
              {% if user.is_authenticated %}
                <p class="lead"> Dynamic id: {{ dynamic_id }} </p>
                <p class="lead"> Actual number of molecules: {{ number_of_existing_molecules }} </p>
              {% else %}
                <p class="lead"> Usuário anônimo </p>
              {% endif %}
            <h2>Include more molecules</h2>
            <div class="form-group">
                <label for="{{ include_molecules_form.number_of_molecules.id_for_label }}">{{ dynamic_form.number_of_molecules.label }}</label>
                {{ include_molecules_form.number_of_molecules.errors }}
                {{ include_molecules_form.number_of_molecules|add_class:"form-control" }}
                <span class="help-block">{% trans 'Enter the number of molecules to be added.' %}</span>
            </div>
            <div class="form-group">
                <div class="btn-group">
                    <button type="reset" class="btn btn-default">{% trans 'Reset' %}</button>
                    <button type="submit" class="btn btn-primary">{% trans 'Next step' %}</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-3"></div>
</div>
{% endblock %}

src/dynamics/templates/dynamics/list_dynamic.html
{% extends 'base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}

<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <h1>{% trans 'List of dynamics for' %}</h1>
    {% if user.is_authenticated %}
      <p class="lead"> {{ user.first_name }} </p>
      <p class="lead"> {{ user.email }} </p>
    {% else %}
      <p class="lead"> Usuário anônimo </p>
    {% endif %}
      {% for dynamic in dynamics %}
          <div class="form-group">
              <div class="col-sm-9">
                <h1><a href="">Dynamic id: {{ dynamic.id }}</a></h1>
                <p>Number of molecules: {{ dynamic.number_of_molecules}}</p>
                <p>Started: {{ dynamic.started|linebreaksbr }}</p>
                <div class="form-group">
                    <div class="btn-group">
                        <a class="btn btn-default" href="{% url 'dynamics:include_molecules' dynamic.id %}" role="button">{% trans "Attach more molecules" %}</a>
                        <!-- <a class="btn btn-default" href="" role="button">{% trans "Attach more molecules" %}</a> <-->
                        <a class="btn btn-default" href="{% url 'dynamics:run_alignment' dynamic.id %}" role="button">{% trans "Run alignment" %}</a>
                        <a class="btn btn-default" href="{% url 'dynamics:lqtagrid_box' dynamic.id 0 0%}" role="button">{% trans "Run LQTAGrid" %}</a>
                    </div>
                </div>
              </div>
          </div>
      {% endfor %}
  </div>
</div>

{% endblock %}

src/dynamics/templates/dynamics/run_alignment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load widget_tweaks %}

{% block head_js %}
<link rel="stylesheet" href="{% static "third-party/magicsuggest/magicsuggest-min.css" %}">
{% endblock %}

{% block footer_js %}
<script src="{% static "third-party/magicsuggest/magicsuggest-min.js" %}"></script>
<script>
    $('#molecules-form').submit(function(event) {

        var numeric_atoms_input_re = /^(\d+)(,\d+)*$/;
        var number_of_inputs = $('#id_form-TOTAL_FORMS').val();
        var i;

        for(i=0; i<number_of_inputs; i++) {
            var input = $('#id_form-' + i + '-atoms').val();
            input = input.replace(/ /g,'');

            if(!numeric_atoms_input_re.test(input) ||
                input.split(',').length != {{ max_atoms_selected }}) {

                $('#id_form-' + i + '-atoms').parent().parent().addClass('has-error');
                $('#id_form-' + i + '-atoms').focus();
                event.preventDefault();
                return false;
            }
        }
        this.submit();
    });
</script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h1>{% trans "Run Alignment" %}</h1>
        <p class="lead">{% trans 'On this page you must insert the reference molecules to the dynamics and alignments.' %}</p>
        <form id="molecules-form" class="form-horizontal" role="form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ dynamic_form.non_field_errors }}
            <div class="form-group">
                <label for="reference-molecule" class="col-sm-3 control-label">{% trans 'Reference' %}</label>
                <div class="col-sm-9">
                    <select id="" name="reference-molecule" class="form-control">
                    {% with ''|center:total_number_of_molecules as range %}
                      {% for f in range %}
                      <option value="{{ forloop.counter0 }}">{% trans 'Molecule' %} #{{ forloop.counter }}</option>
                      {% endfor %}
                    {% endwith %}
                    </select>
                </div>
            </div>
            {{ molecule_formset.management_form }}
            {% for m,f in molecules_attached %}
              <hr>
              <div class="form-group">
                <p>Molecule #{{ forloop.counter }}: {{ m.file.path }}</p>
              </div>
              <div class="form-group atoms-input">
                  <label for="{{ f.atoms.id_for_label }}" class="col-sm-3 control-label">Atoms</label>
                  <div class="col-sm-9">
                      {{ f.atoms.errors }}
                      {{ f.atoms|add_class:'numeric-atom' }}
                  </div>
              </div>
            {% endfor %}
            <div class="form-group">
              <!--<label for="{{ dynamic_form.run_lqtagrid.id_for_label }}" class="col-sm-3 control-label">{{ dynamic_form.run_lqtagrid.label }}</label> -->
              <label for="id_run_lqtagrid" class="col-sm-3 control-label">Run lqtagrid</label>
              <div class="col-sm-3">
                <!--{{ dynamic_form.run_lqtagrid.errors }}
                {{ dynamic_form.run_lqtagrid|add_class:"form-control" }} <-->
                <input class="form-control" id="id_run_lqtagrid" name="run_lqtagrid" type="checkbox">
              </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-3 control-label"></label>
                <div class="col-sm-offset-3 col-sm-9">
                      <button type="submit" class="btn btn-default">{% trans 'Start Alignment' %}</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-3"></div>
</div>
{% endblock %}